services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=tasksapp
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  admin:
    image: nginx:latest
    ports:
      - '8000:80'
    volumes:
      - ./backend:/var/www/html
      - ./backend/config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    image: php:8-fpm
    volumes:
      - ./backend:/var/www/html

  api:
    build: 
      context: ./api
    volumes:
      - ./api:/app
    working_dir: /app
    ports:
     - '5000:5000'
    depends_on:
      db:
        condition: service_healthy
  frontend:
    image: nginx:latest
volumes:
  mysql_data: