services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - mysql_data:/var/lib/mysql
  admin:
    image: nginx:latest
    ports:
      - '8000:80'
    volumes:
      - ./backend:/var/www/html
      - ./backend/config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:8-fpm
    volumes:
      - ./backend:/var/www/html

  api:
    image: python:latest
  frontend:
    image: nginx:latest
volumes:
  mysql_data: